title: AIC LLSM Processing
description: Documentation for LLSM image preprocessing code used by the Advanced Imaging Center (AIC), Janelia Research Campus.
theme: just-the-docs

url: http://llsm.aicjanelia.org/

aux_links:
  LLSM on GitHub: https://github.com/aicjanelia/LLSM

# External navigation links
nav_external_links:
  - title: LLSM on GitHub
    url: https://github.com/aicjanelia/LLSM
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false

math: mathjax
